---

- name: check source hostname prefix
  when:
    - source_host is defined
  set_fact:
    __source_host: >-
      {{  (source_host.startswith('http://') or source_host.startswith('https://'))
      | ternary (source_host, source_host | regex_replace('^(.*)$', 'http://\\1')) }}

- name: check destination hostname prefix
  when:
    - destination_host is defined
  set_fact:
    __dest_host: >-
      {{  (destination_host.startswith('http://') or destination_host.startswith('https://'))
      | ternary (destination_host, (destination_host | regex_replace('^(.*)$', 'http://\\1'))) }}

- name: get saved objects from kibana
  when:
    - __source_host is defined
  uri:
    method: GET
    url: "{{ __source_host }}/api/saved_objects/_find?{{ source_parameters }}"
    return_content: true
    validate_certs: "{{ validate_certs }}"
    headers:
      kbn-xsrf: true
      Content-Type: 'application/json'
  register: objects
  changed_when: objects.status == 200
  notify: save return objects to file
  tags: get

- name: read file contents
  when:
    - source_file is defined
  set_fact:
    file_contents: "{{ lookup('file', source_file) | from_json }}"
  tags: post

- name: post saved objects to kibana
  when:
    - __dest_host is defined
  uri:
    method: POST
    url: "{{ __dest_host }}/api/saved_objects/_bulk_create?{{ destination_parameters }}"
    body: "{{ ((source_objects | default([])) + lookup('template', 'normalize_saved_objects.j2') + (file_contents | default([]))) | to_json }}"
    body_format: 'json'
    validate_certs: "{{ validate_certs }}"
    headers:
      kbn-xsrf: true
      Content-Type: 'application/json'
  register: response
  changed_when: response.status == 200
  tags: post
