---

- name: check source hostname prefix
  when:
    - source['host'] is defined
  set_fact:
    source_host: >-
      {{  (source['host'].startswith('http://') or source['host'].startswith('https://'))
      | ternary (source['host'], source['host'] | regex_replace('^(.*)$', 'http://\\1')) }}

- name: check destination hostname prefix
  when:
    - destination['host'] is defined
  set_fact:
    dest_host: >-
      {{  (destination['host'].startswith('http://') or destination['host'].startswith('https://'))
      | ternary (destination['host'], (destination['host'] | regex_replace('^(.*)$', 'http://\\1'))) }}

- name: get saved objects from kibana
  when:
    - source_host is defined
  uri:
    method: GET
    url: "{{ source_host }}/api/saved_objects/_find?{{ source['parameters'] }}"
    return_content: true
    validate_certs: "{{ validate_certs }}"
    headers:
      kbn-xsrf: true
      Content-Type: 'application/json'
  register: objects
  changed_when: objects.status == 200
  notify: save return objects to file
  tags: get

- name: read file contents
  when:
    - source['file'] is defined
  set_fact:
    file_contents: "{{ lookup('file', source['file']) | from_json }}"
  tags: post

- name: post saved objects to kibana
  when:
    - dest_host is defined
  uri:
    method: POST
    url: "{{ dest_host }}/api/saved_objects/_bulk_create?{{ destination['parameters'] }}"
    body: "{{ (source.get('objects', []) + lookup('template', 'normalize_saved_objects.j2') + (file_contents | default([]))) | to_json }}"
    body_format: 'json'
    validate_certs: "{{ validate_certs }}"
    headers:
      kbn-xsrf: true
      Content-Type: 'application/json'
  register: response
  changed_when: response.status == 200
  tags: post
